### ISSUE TITLE
MISP to STIX converter using a single indicator for all attributes

### ISSUE THREAD

**Issue by iglocska** [MISP/MISP-STIX-Converter#22]
Currently (unless I am mistaken), all attributes are added as observables to a single indicator during the conversion (https://github.com/MISP/MISP-STIX-Converter/blob/master/misp_stix_converter/converters/convert.py#L67), however this is most of the time not correct for the actual data. Each attribute should be treated as a separate indicator with 1-2 observables each (For example a filename|sha1 type would translate to an indicator with 2 observables).

**Comment by FloatingGhost** [comment]
don't wanna :<

eh but I guess I have to. It makes sense.

Shouldn't be *too* hard I guess. Just tedious.

**Comment by iglocska** [comment]
Sorry <3

**Comment by iglocska** [comment]
Perfect, thanks!
