### ISSUE TITLE
US-Cert STIX Files

### ISSUE THREAD

**Issue by zeroq** [MISP/MISP-STIX-Converter#25]
Hi, if you include "import stix.extensions.marking.ais" in your imports before trying to load Stix file from XML it works fine without the need to remove  US-Cert markings. 

From the documentation of StixProject:

If you are writing code that needs to parse AIS markings, make sure that your
program imports this module before beginning to parse any STIX documents:
.. code-block:: python
    import stix.extensions.marking.ais

**Comment by FloatingGhost** [comment]
yeah I could but there's literally no reason to

works as is, so I'm not going to maybe break it by trying to include the esoteric marking formats of some random cert
