### ISSUE TITLE
TypeError: search_index() got an unexpected keyword argument 'dateto'

### ISSUE THREAD

**Issue by CQRuu** [MISP/MISP-STIX-Converter#9]
I received the following error when trying to convert misp-to-stix:

**My command:**
`misp-to-stix.py -t tlp:white -o out.{}.xml -c /home/misp/misp-t2/bin/MISP-STIX-Converter/misp.login
`  
or
  `misp-to-stix.py -i 46874 --format xml -o 46874.xml -c /home/misp/misp-t2/bin/MISP-STIX-Converter/misp.login`

**Error message:**
```
Traceback (most recent call last):
  File "misp-to-stix.py", line 83, in <module>
    package = MISP.pull(args.eid)[0]
  File "/usr/local/lib/python3.4/dist-packages/misp_stix_converter-0.2.7-py3.4.egg/misp_stix_converter/servers/misp.py", line 67, in pull
TypeError: search_index() got an unexpected keyword argument 'dateto'


MISP version: 2.4.67
```

**Comment by FloatingGhost** [comment]
You're using an old version of the converter

You're using `0.2.7`, latest version is `0.2.9`, please run a git pull, re-install and try again

**Comment by CQRuu** [comment]
Thanks for pointing it out! upgraded version to 0.2.9 and it works now.
Thank you :D
